// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	QuotaBucInfo        *quotaBucInfo
	QuotaDatasetInfo    *quotaDatasetInfo
	QuotaDatasourceInfo *quotaDatasourceInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	QuotaBucInfo = &Q.QuotaBucInfo
	QuotaDatasetInfo = &Q.QuotaDatasetInfo
	QuotaDatasourceInfo = &Q.QuotaDatasourceInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		QuotaBucInfo:        newQuotaBucInfo(db, opts...),
		QuotaDatasetInfo:    newQuotaDatasetInfo(db, opts...),
		QuotaDatasourceInfo: newQuotaDatasourceInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	QuotaBucInfo        quotaBucInfo
	QuotaDatasetInfo    quotaDatasetInfo
	QuotaDatasourceInfo quotaDatasourceInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		QuotaBucInfo:        q.QuotaBucInfo.clone(db),
		QuotaDatasetInfo:    q.QuotaDatasetInfo.clone(db),
		QuotaDatasourceInfo: q.QuotaDatasourceInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		QuotaBucInfo:        q.QuotaBucInfo.replaceDB(db),
		QuotaDatasetInfo:    q.QuotaDatasetInfo.replaceDB(db),
		QuotaDatasourceInfo: q.QuotaDatasourceInfo.replaceDB(db),
	}
}

type queryCtx struct {
	QuotaBucInfo        IQuotaBucInfoDo
	QuotaDatasetInfo    IQuotaDatasetInfoDo
	QuotaDatasourceInfo IQuotaDatasourceInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		QuotaBucInfo:        q.QuotaBucInfo.WithContext(ctx),
		QuotaDatasetInfo:    q.QuotaDatasetInfo.WithContext(ctx),
		QuotaDatasourceInfo: q.QuotaDatasourceInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
