// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuotaDatasourceInfo = "quota_datasource_info"

// QuotaDatasourceInfo mapped from table <quota_datasource_info>
type QuotaDatasourceInfo struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null;comment:数据源名称" json:"name"`                               // 数据源名称
	Type       string    `gorm:"column:type;not null;comment:数据源类型" json:"type"`                               // 数据源类型
	Desc       string    `gorm:"column:desc;comment:数据源描述" json:"desc"`                                        // 数据源描述
	Connect    string    `gorm:"column:connect;comment:连接信息" json:"connect"`                                   // 连接信息
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDeleted  int32     `gorm:"column:is_deleted" json:"is_deleted"`
}

// TableName QuotaDatasourceInfo's table name
func (*QuotaDatasourceInfo) TableName() string {
	return TableNameQuotaDatasourceInfo
}
