// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQuotaBucInfo = "quota_buc_info"

// QuotaBucInfo 业务域目录管理表

type QuotaBucInfo struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GUID       string    `gorm:"column:guid;primaryKey;comment:业务流程id" json:"guid"`                            // 业务流程id
	BucName    string    `gorm:"column:buc_name;comment:业务流程名称" json:"buc_name"`                               // 业务流程名称
	BucDesc    string    `gorm:"column:buc_desc;comment:描述" json:"buc_desc"`                                   // 描述
	BucStatus  int32     `gorm:"column:buc_status;comment:业务流程状态" json:"buc_status"`                           // 业务流程状态
	BucTags    string    `gorm:"column:buc_tags;comment:业务流程标签" json:"buc_tags"`                               // 业务流程标签
	DsID       int32     `gorm:"column:ds_id;not null;comment:数据集id" json:"ds_id"`                             // 数据集id
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDeleted  int32     `gorm:"column:is_deleted;comment:是否删除" json:"is_deleted"`                             // 是否删除
}

// TableName QuotaBucInfo's table name
func (*QuotaBucInfo) TableName() string {
	return TableNameQuotaBucInfo
}
